/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

/**
 *
 * @author Fatlem
 */
public class FrameLaporanKejadian extends javax.swing.JFrame {

    /**
     * Creates new form FarmeLaporanKejadian
     */
    public FrameLaporanKejadian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_tmbh = new javax.swing.JButton();
        btn_menu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laporan Kejadian");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        btn_tmbh.setBackground(new java.awt.Color(24, 45, 74));
        btn_tmbh.setForeground(new java.awt.Color(255, 255, 255));
        btn_tmbh.setText("Tambah Kejadian");
        btn_tmbh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbhActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tmbh, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        btn_menu1.setBackground(new java.awt.Color(24, 45, 74));
        btn_menu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu1.setText("Menu Utama");
        btn_menu1.setBorder(null);
        btn_menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/Laporan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(816, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbhActionPerformed
        FrameTambahLaporan TB = new FrameTambahLaporan();
        TB.show();
        
        dispose();
    }//GEN-LAST:event_btn_tmbhActionPerformed

    private void btn_menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu1ActionPerformed
        FrameMenuUtama MU = new FrameMenuUtama();
        MU.show();
        
        dispose();
    }//GEN-LAST:event_btn_menu1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu1;
    private javax.swing.JButton btn_tmbh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
