/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.util.ArrayList;
import javax.swing.JFrame;
/**
 *
 * @author Fatlem
 */
public class FrameMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenuUtama
     */
    public FrameMenuUtama() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pdb = new javax.swing.JToggleButton();
        btn_pc = new javax.swing.JToggleButton();
        btn_lk = new javax.swing.JToggleButton();
        btn_ks = new javax.swing.JToggleButton();
        btn_kd = new javax.swing.JToggleButton();
        btn_ip = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pdb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/pdb.png"))); // NOI18N
        btn_pdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdbActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        btn_pc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/pc.png"))); // NOI18N
        btn_pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pcActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        btn_lk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/lk.png"))); // NOI18N
        btn_lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        btn_ks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/pk.png"))); // NOI18N
        btn_ks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ksActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ks, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        btn_kd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/kd.png"))); // NOI18N
        btn_kd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kdActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        btn_ip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/ia.png"))); // NOI18N
        btn_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ipActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/Menu_Utama2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(816, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdbActionPerformed
        FramePeta P = new FramePeta();
        P.show();
        
        dispose();
    }//GEN-LAST:event_btn_pdbActionPerformed

    private void btn_pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pcActionPerformed
        FramePerkiraanCuaca PC = new FramePerkiraanCuaca();
        PC.show();
        
        dispose();
    }//GEN-LAST:event_btn_pcActionPerformed

    private void btn_lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lkActionPerformed
        FrameLaporanKejadian LK = new FrameLaporanKejadian();
        LK.show();
        
        dispose();
    }//GEN-LAST:event_btn_lkActionPerformed

    private void btn_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ipActionPerformed
        FrameInfoAplikasi IP = new FrameInfoAplikasi();
        IP.show();
        
        dispose();
    }//GEN-LAST:event_btn_ipActionPerformed

    private void btn_ksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ksActionPerformed
        FramePanduanKeselamatan PK = new FramePanduanKeselamatan();
        PK.show();
        
        dispose();
    }//GEN-LAST:event_btn_ksActionPerformed

    private void btn_kdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kdActionPerformed
        FrameKontak K = new FrameKontak();
        K.show();
        
        dispose();
    }//GEN-LAST:event_btn_kdActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_ip;
    private javax.swing.JToggleButton btn_kd;
    private javax.swing.JToggleButton btn_ks;
    private javax.swing.JToggleButton btn_lk;
    private javax.swing.JToggleButton btn_pc;
    private javax.swing.JToggleButton btn_pdb;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
  
}
