/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Fatlem
 */
public class FrameTambahLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FrameTambahLaporan
     */
    public FrameTambahLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p_nama = new javax.swing.JTextField();
        p_tempat = new javax.swing.JTextField();
        p_tgl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_desc = new javax.swing.JTextArea();
        btn_kirim = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menu.setBackground(new java.awt.Color(24, 45, 74));
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("Menu Utama");
        btn_menu.setBorder(null);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perkiraan Cuaca");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(135, 224, 230));
        jLabel3.setText("Deskripsi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(135, 224, 230));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(135, 224, 230));
        jLabel5.setText("Tempat Kejadian");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(135, 224, 230));
        jLabel6.setText("Tanggal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        p_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_namaActionPerformed(evt);
            }
        });
        getContentPane().add(p_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 280, -1));

        p_tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_tempatActionPerformed(evt);
            }
        });
        getContentPane().add(p_tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 280, -1));

        p_tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_tglActionPerformed(evt);
            }
        });
        getContentPane().add(p_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 280, -1));

        p_desc.setColumns(20);
        p_desc.setRows(5);
        p_desc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                p_descAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(p_desc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 280, 70));

        btn_kirim.setBackground(new java.awt.Color(24, 45, 74));
        btn_kirim.setForeground(new java.awt.Color(135, 224, 230));
        btn_kirim.setText("Kirim");
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/TambahLaporan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        setSize(new java.awt.Dimension(816, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        FrameMenuUtama MU = new FrameMenuUtama();
        MU.show();
        
        dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void p_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_namaActionPerformed

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        String nama = p_nama.getText().trim();
        String tempat = p_tempat.getText().trim();
        String tanggal = p_tgl.getText().trim();
        String desc = p_desc.getText().trim();

        if (nama.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harus Diisi");
        } else {
            try {
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO laporan (nama, tempat, tanggal, deskripsi) VALUES (?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, nama);
                p.setString(2, tempat);
                p.setString(3, tanggal);
                p.setString(4, desc);

                p.executeUpdate();
                JOptionPane.showMessageDialog(null, "Laporan Terkirim");
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error occurred while creating account");
            }
        }
    }//GEN-LAST:event_btn_kirimActionPerformed

    private void p_tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_tglActionPerformed

    private void p_tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_tempatActionPerformed

    private void p_descAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_p_descAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_p_descAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_kirim;
    private javax.swing.JButton btn_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea p_desc;
    private javax.swing.JTextField p_nama;
    private javax.swing.JTextField p_tempat;
    private javax.swing.JTextField p_tgl;
    // End of variables declaration//GEN-END:variables
}
